#@data/values

---

deployment:
  instances: 6
  image: vfarcic/devops-toolkit-series:latest
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 125m
      memory: 128Mi
