---

apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: devops-toolkit
spec:
  serviceAccountName: kapp
  fetch:
  - git:
      url: https://github.com/vfarcic/carvel-demo
      ref: origin/main
      subPath: kapp-controller
  template:
  - ytt: {}
  deploy:
  - kapp: {}
