---

apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: devops-toolkit
spec:
  serviceAccountName: kapp
  fetch:
  - git:
      url: https://github.com/vfarcic/carvel-demo
      ref: origin/main
      subPath: kapp-controller
  template:
  - ytt: {}
  - ytt:
      inline:
        pathsFrom:
        - secretRef:
            name: devops-toolkit
  deploy:
  - kapp: {}

---

apiVersion: v1
kind: Secret
metadata:
  name: devops-toolkit
stringData:
  values2.yml: |
    #@data/values
    ---
    deployment:
      image: vfarcic/devops-toolkit-series:2.7.0
